export { BasicCollection } from './collection/basic-collection.interface';
export { BasicDigitalPublicationFormat } from './digital-publication-format/basic-digital-publication-format.interface';
export { BasicPublication } from './publication/basic-publication.interface';
export { Collection } from './collection/collection.interface';
export { DigitalPublicationFormat } from './digital-publication-format/digital-publication-format.interface';
export { GamiBooksModule } from './gami-books.module';
export { Publication } from './publication/publication.interface';
export { PublicationCoverType } from './publication/publication-cover-type.enum';
export { Reader } from './reader/reader.interface';
