
export enum SubjectAlias {
    ACTIONS = 'actions',
    ADDRESSES = 'addresses',
    APP_FEATURES = 'app_features',
    APP_INSTANCES = 'app_instances',
    APP_PLANS = 'app_plans',
    APPS = 'apps',
    AUTHORS = 'authors',
    CITIES = 'cities',
    COLLECTIONS = 'collections',
    COUNTRIES = 'countries',
    COVERS = 'covers',
    CUSTOMERS = 'customers',
    DIGITAL_PUBLICATION_FORMATS = 'digital_publication_formats',
    EMAILS = 'emails',
    FILES = 'files',
    INCOMES = 'incomes',
    ILLUSTRATORS = 'illustrators',
    LANGUAGES = 'languages',
    MARITAL_STATUSES = 'marital_statuses',
    MENUS = 'menus',
    OCCUPATIONS = 'occupations',
    ORGANIZATIONS = 'organizations',
    PERMISSIONS = 'permissions',
    PERSONS = 'persons',
    PHONES = 'phones',
    PUBLICATIONS = 'publications',
    PUBLISHERS = 'publishers',
    READERS = 'readers',
    ROLES = 'roles',
    STATES = 'states',
    SUBJECTS = 'subjects',
    TRANSLATIONS = 'translations',
    TRANSLATORS = 'translators',
    USERS = 'users',
}
