import { Author } from '../author/author.interface';
import { City } from '../../location/city/city.interface';
import { Collection } from '../collection/collection.interface';
import { DigitalPublicationFormat } from '../digital-publication-format/digital-publication-format.interface';
import { Illustrator } from '../illustrator/illustrator.interface';
import { Language } from '../../core/i18n/language/language.interface';
import { MonetaryValue } from '../../domain/monetary/monetary-value.interface';
import { PublicationCoverType } from './publication-cover-type.enum';
import { QuantitativeValue } from '../../core/value/quantitative-value.interface';
import { Reader } from '../reader/reader.interface';
import { Translator } from '../translator/translator.interface';
import { User } from '../../user/user.interface';

export interface BasicPublication {
    title: string;
    isActive: boolean;
    language: Language;
    creator: User;
    isDigital: boolean;
    parentCollection: Collection;
    subTitle?: string;
    authors?: Array<Author>;
    illustrators?: Array<Illustrator>;
    publisher?: string;
    translators?: Array<Translator>;
    description?: string;
    contentRating?: string;
    friendlyUrl?: string;
    digitalPublicationFormat?: DigitalPublicationFormat;
    sizeBytes?: number;
    quality?: number;
    code?: string;
    number?: string;
    numberOfPages?: number;
    year?: number;
    image?: string;
    isbn10?: string;
    isbn13?: string;
    dimensions?: Array<QuantitativeValue>;
    weight?: QuantitativeValue;
    publicationCoverType?: PublicationCoverType;
    edition?: string;
    city?: City;
    url?: string;
    tags?: Array<string>;
    price?: MonetaryValue;
    extraContent?: string;
    purchasedAt?: Date;
    readers?: Array<Reader>;
    currentReader?: Reader;
    waitingList?: Array<Reader>;
    sourcePublicationId?: string;
    createdAt?: Date;
    lastUpdate?: Date;
}
