export enum PasswordValidationErrors {
    MIN_LENGHT_8,
    MAX_LENGHT_20,
    AT_LEAST_ONE_LOWERCASE_LETTER,
    AT_LEAST_ONE_UPPERCASE_LETTER,
    AT_LEAST_ONE_NUMBER,
    AT_LEAST_ONE_SPECIAL_CHAR,
    SEQUENTIAL_CHARS,
    REPEATED_CHARS,
    INVALID_CHARS,
}
