export enum DomainType {
    EDUCATION_LEVEL = 'EDUCATION_LEVEL',
    GENDER = 'GENDER',
    INCOME = 'INCOME',
    MARITAL_STATUS = 'MARITAL_STATUS',
    OCCUPATION = 'OCCUPATION',
    DIGITAL_PUBLICATION_FORMAT = 'DIGITAL_PUBLICATION_FORMAT',
    PUBLICATION_COVER_TYPE = 'PUBLICATION_COVER_TYPE',
}
